// Generated by tools/bundle_ide.mjs from ide/flash/an3155.js, ide/flash/dfuse.js, ide/doom-sim.js, ide/browser-build.js, ide/app.js - do not edit.
(() => {
"use strict";
// ---- ide/flash/an3155.js
// STM32 ROM UART bootloader (ST application note AN3155).
//
// Works for both targets over USART1 (PA9 TX / PA10 RX) with BOOT0 high:
//   STM32F103C8 (Blue Pill)  PID 0x410, 1 KB pages,   Erase (0x43)
//   STM32H743                PID 0x450, 128 KB sectors, Extended Erase (0x44)
//
// The transport is anything with write(Uint8Array) and read(n, timeoutMs);
// webSerialTransport() adapts a Web Serial port (8E1, even parity).

const ACK = 0x79;
const NACK = 0x1f;

const CHIPS = {
  0x410: { name: 'STM32F103 (medium density)', flashBase: 0x08000000, eraseUnit: 1024 },
  0x450: { name: 'STM32H743/753', flashBase: 0x08000000, eraseUnit: 128 * 1024, writeAlign: 32 },
};

class BootloaderError extends Error {}

class An3155 {
  constructor(transport, log = () => {}) {
    this.t = transport;
    this.log = log;
    this.commands = [];
  }

  async ack(timeout = 1000, what = 'command') {
    const b = (await this.t.read(1, timeout))[0];
    if (b === ACK) return;
    if (b === NACK) throw new BootloaderError(`${what}: NACK from bootloader`);
    throw new BootloaderError(`${what}: unexpected byte 0x${b.toString(16)}`);
  }

  async sendCommand(cmd, timeout) {
    await this.t.write(Uint8Array.of(cmd, cmd ^ 0xff));
    await this.ack(timeout, `command 0x${cmd.toString(16)}`);
  }

  static withChecksum(bytes) {
    let x = 0;
    for (const b of bytes) x ^= b;
    return Uint8Array.from([...bytes, x]);
  }

  async sendAddress(addr) {
    const a = [(addr >>> 24) & 0xff, (addr >>> 16) & 0xff, (addr >>> 8) & 0xff, addr & 0xff];
    await this.t.write(An3155.withChecksum(a));
    await this.ack(1000, 'address');
  }

  async connect() {
    // 0x7F lets the bootloader measure the baud rate. If it was already
    // synchronised it answers NACK (or nothing), which is also fine.
    await this.t.write(Uint8Array.of(0x7f));
    try {
      await this.ack(500, 'sync');
    } catch (e) {
      if (!(e instanceof BootloaderError) && !/timeout/i.test(e.message)) throw e;
    }
    await this.get();
    this.pid = await this.getId();
    this.chip = CHIPS[this.pid];
    this.log(`bootloader v${this.version >> 4}.${this.version & 15}, chip ID 0x${this.pid.toString(16)}` +
      (this.chip ? ` (${this.chip.name})` : ' (unknown)'));
    if (!this.chip) throw new BootloaderError(`unsupported chip ID 0x${this.pid.toString(16)}`);
    return this.chip;
  }

  async get() {
    await this.sendCommand(0x00);
    const n = (await this.t.read(1, 1000))[0];
    const data = await this.t.read(n + 1, 1000);
    await this.ack();
    this.version = data[0];
    this.commands = Array.from(data.slice(1));
  }

  async getId() {
    await this.sendCommand(0x02);
    const n = (await this.t.read(1, 1000))[0];
    const id = await this.t.read(n + 1, 1000);
    await this.ack();
    return (id[0] << 8) | id[1];
  }

  async readMemory(addr, length) {
    await this.sendCommand(0x11);
    await this.sendAddress(addr);
    await this.t.write(Uint8Array.of(length - 1, (length - 1) ^ 0xff));
    await this.ack(1000, 'read length');
    return this.t.read(length, 2000);
  }

  async writeMemory(addr, data) {
    await this.sendCommand(0x31);
    await this.sendAddress(addr);
    const frame = new Uint8Array(data.length + 2);
    frame[0] = data.length - 1;
    frame.set(data, 1);
    let x = frame[0];
    for (const b of data) x ^= b;
    frame[frame.length - 1] = x;
    await this.t.write(frame);
    await this.ack(2000, `write at 0x${addr.toString(16)}`);
  }

  // Erases the erase units (pages or sectors) covering [base, base + length).
  async erase(length) {
    const unit = this.chip.eraseUnit;
    const count = Math.ceil(length / unit);
    const pages = Array.from({ length: count }, (_, i) => i);
    if (this.commands.includes(0x44)) {
      await this.sendCommand(0x44);
      const frame = [((count - 1) >> 8) & 0xff, (count - 1) & 0xff];
      for (const p of pages) frame.push((p >> 8) & 0xff, p & 0xff);
      let x = 0;
      for (const b of frame) x ^= b;
      await this.t.write(Uint8Array.from([...frame, x]));
      await this.ack(count * 4000 + 10000, 'extended erase');
    } else {
      await this.sendCommand(0x43);
      const frame = [count - 1, ...pages];
      let x = 0;
      for (const b of frame) x ^= b;
      await this.t.write(Uint8Array.from([...frame, x]));
      await this.ack(count * 100 + 5000, 'erase');
    }
  }

  async go(addr) {
    await this.sendCommand(0x21);
    await this.sendAddress(addr);
  }

  // Erase, program, verify and start `image` at the start of flash.
  async flash(image, { onProgress = () => {}, verify = true, start = true } = {}) {
    const chip = this.chip || (await this.connect());
    const base = chip.flashBase;
    const align = chip.writeAlign || 4;
    const padded = new Uint8Array(Math.ceil(image.length / align) * align).fill(0xff);
    padded.set(image);

    this.log(`erasing ${Math.ceil(padded.length / chip.eraseUnit)} x ${chip.eraseUnit / 1024} KB`);
    onProgress('erase', 0, 1);
    await this.erase(padded.length);
    onProgress('erase', 1, 1);

    for (let off = 0; off < padded.length; off += 256) {
      await this.writeMemory(base + off, padded.subarray(off, Math.min(off + 256, padded.length)));
      onProgress('write', Math.min(off + 256, padded.length), padded.length);
    }

    if (verify) {
      for (let off = 0; off < image.length; off += 256) {
        const n = Math.min(256, image.length - off);
        const got = await this.readMemory(base + off, n);
        for (let i = 0; i < n; i++) {
          if (got[i] !== image[off + i]) {
            throw new BootloaderError(`verify failed at 0x${(base + off + i).toString(16)}`);
          }
        }
        onProgress('verify', off + n, image.length);
      }
    }
    if (start) {
      await this.go(base);
      this.log('started application');
    }
  }
}

// Adapts a Web Serial SerialPort (already requested by the page).
async function webSerialTransport(port, baudRate = 115200) {
  await port.open({ baudRate, dataBits: 8, parity: 'even', stopBits: 1 });
  const writer = port.writable.getWriter();
  const reader = port.readable.getReader();
  let buf = new Uint8Array(0);
  let pending = null;

  const pump = async () => {
    const { value, done } = await reader.read();
    if (done) throw new Error('serial port closed');
    const next = new Uint8Array(buf.length + value.length);
    next.set(buf);
    next.set(value, buf.length);
    buf = next;
  };

  return {
    async write(bytes) {
      await writer.write(bytes);
    },
    async read(n, timeoutMs) {
      const deadline = Date.now() + timeoutMs;
      while (buf.length < n) {
        const left = deadline - Date.now();
        if (left <= 0) throw new Error(`timeout waiting for ${n} byte(s)`);
        pending = pending || pump().finally(() => { pending = null; });
        await Promise.race([pending, new Promise((r) => setTimeout(r, left))]);
      }
      const out = buf.slice(0, n);
      buf = buf.slice(n);
      return out;
    },
    async close() {
      reader.cancel().catch(() => {});
      reader.releaseLock();
      writer.releaseLock();
      await port.close();
    },
  };
}

// ---- ide/flash/dfuse.js
// STM32 ROM USB DFU bootloader (DfuSe, ST's DFU 1.1a extensions) over WebUSB.
//
// The STM32H743 enumerates as 0483:DF11 on PA11/PA12 when started with
// BOOT0 high. (The STM32F103's ROM has no USB bootloader; use AN3155.)
//
// `usb` is a WebUSB USBDevice or anything with the same open /
// selectConfiguration / claimInterface / controlTransferIn/Out methods.

const DNLOAD = 1, GETSTATUS = 3, CLRSTATUS = 4, ABORT = 6;
const STATE = { IDLE: 2, DNBUSY: 4, DNLOAD_IDLE: 5, MANIFEST: 7, ERROR: 10 };

const DFU_FILTERS = [{ vendorId: 0x0483, productId: 0xdf11 }];

class DfuError extends Error {}

// "@Internal Flash  /0x08000000/16*128Kg" -> [{ start, sectorSize, count }]
function parseDfuseLayout(name) {
  const m = /\/\s*(0x[0-9a-fA-F]+)\s*\/(.*)$/.exec(name);
  if (!m) return null;
  let addr = parseInt(m[1], 16);
  const segments = [];
  // Several banks can follow as "/0x08100000/8*128Kg"
  for (const part of m[2].split('/')) {
    if (/^0x/i.test(part.trim())) {
      addr = parseInt(part.trim(), 16);
      continue;
    }
    for (const seg of part.split(',')) {
      const s = /(\d+)\s*\*\s*(\d+)\s*([KM]?)\s*([a-g])?/.exec(seg.trim());
      if (!s) continue;
      const mult = s[3] === 'K' ? 1024 : s[3] === 'M' ? 1024 * 1024 : 1;
      const size = parseInt(s[2], 10) * mult;
      const count = parseInt(s[1], 10);
      segments.push({ start: addr, sectorSize: size, count, attrs: s[4] || '' });
      addr += size * count;
    }
  }
  return segments;
}

class DfuSe {
  constructor(usb, log = () => {}) {
    this.dev = usb;
    this.log = log;
    this.transferSize = 1024;
  }

  async open() {
    await this.dev.open();
    if (this.dev.configuration === null) await this.dev.selectConfiguration(1);

    const alts = [];
    for (const intf of this.dev.configuration.interfaces) {
      for (const alt of intf.alternates) {
        if (alt.interfaceClass === 0xfe && alt.interfaceSubclass === 0x01) {
          alts.push({ intf: intf.interfaceNumber, alt: alt.alternateSetting, name: alt.interfaceName || '' });
        }
      }
    }
    const flash = alts.find((a) => /flash/i.test(a.name)) || alts[0];
    if (!flash) throw new DfuError('no DFU interface found');
    this.intf = flash.intf;
    await this.dev.claimInterface(this.intf);
    await this.dev.selectAlternateInterface(this.intf, flash.alt);
    this.layout = parseDfuseLayout(flash.name) || [
      { start: 0x08000000, sectorSize: 128 * 1024, count: 16, attrs: 'g' },
    ];
    this.transferSize = (await this.readTransferSize()) || this.transferSize;
    this.log(`DFU: ${flash.name.trim() || 'internal flash'}, transfer size ${this.transferSize}`);
    await this.clearErrors();
  }

  async readTransferSize() {
    try {
      const r = await this.dev.controlTransferIn(
        { requestType: 'standard', recipient: 'device', request: 6, value: 0x0200, index: 0 }, 1024);
      const d = new Uint8Array(r.data.buffer, r.data.byteOffset, r.data.byteLength);
      for (let i = 0; i + 1 < d.length && d[i] > 0; i += d[i]) {
        if (d[i + 1] === 0x21 && d[i] >= 7) return d[i + 5] | (d[i + 6] << 8);   // DFU functional
      }
    } catch { /* fall back to default */ }
    return 0;
  }

  async out(request, value, data) {
    const r = await this.dev.controlTransferOut(
      { requestType: 'class', recipient: 'interface', request, value, index: this.intf }, data);
    if (r.status !== 'ok') throw new DfuError(`control OUT ${request} failed: ${r.status}`);
  }

  async getStatus() {
    const r = await this.dev.controlTransferIn(
      { requestType: 'class', recipient: 'interface', request: GETSTATUS, value: 0, index: this.intf }, 6);
    const d = new Uint8Array(r.data.buffer, r.data.byteOffset, r.data.byteLength);
    return { status: d[0], pollMs: d[1] | (d[2] << 8) | (d[3] << 16), state: d[4] };
  }

  async clearErrors() {
    let s = await this.getStatus();
    if (s.state === STATE.ERROR) {
      await this.out(CLRSTATUS, 0);
      s = await this.getStatus();
    }
    if (s.state !== STATE.IDLE && s.state !== STATE.DNLOAD_IDLE) {
      await this.out(ABORT, 0);
    }
  }

  // Sends a DNLOAD and waits until the device has finished it.
  async download(blockNum, data) {
    await this.out(DNLOAD, blockNum, data);
    for (;;) {
      const s = await this.getStatus();
      if (s.status !== 0) throw new DfuError(`DFU status error ${s.status} (state ${s.state})`);
      if (s.state === STATE.DNLOAD_IDLE || s.state === STATE.IDLE) return s;
      if (s.state === STATE.MANIFEST) return s;
      if (s.state === STATE.ERROR) throw new DfuError('device entered dfuERROR');
      await new Promise((r) => setTimeout(r, Math.max(s.pollMs, 1)));
    }
  }

  static addrCommand(cmd, addr) {
    return Uint8Array.of(cmd, addr & 0xff, (addr >>> 8) & 0xff, (addr >>> 16) & 0xff, (addr >>> 24) & 0xff);
  }

  async setAddress(addr) {
    await this.download(0, DfuSe.addrCommand(0x21, addr));
  }

  async eraseSector(addr) {
    await this.download(0, DfuSe.addrCommand(0x41, addr));
  }

  sectorsFor(start, length) {
    const out = [];
    for (const seg of this.layout) {
      for (let i = 0; i < seg.count; i++) {
        const a = seg.start + i * seg.sectorSize;
        if (a < start + length && a + seg.sectorSize > start) out.push(a);
      }
    }
    return out;
  }

  async flash(image, { base = 0x08000000, onProgress = () => {}, start = true } = {}) {
    // The H7 programs 256-bit flash words: pad the tail with erased bytes.
    const padded = new Uint8Array(Math.ceil(image.length / 32) * 32).fill(0xff);
    padded.set(image);
    image = padded;
    const sectors = this.sectorsFor(base, image.length);
    for (let i = 0; i < sectors.length; i++) {
      await this.eraseSector(sectors[i]);
      onProgress('erase', i + 1, sectors.length);
    }
    this.log(`erased ${sectors.length} sector(s)`);

    for (let off = 0; off < image.length; off += this.transferSize) {
      await this.setAddress(base + off);
      await this.download(2, image.subarray(off, Math.min(off + this.transferSize, image.length)));
      onProgress('write', Math.min(off + this.transferSize, image.length), image.length);
    }

    if (start) {
      // Zero-length DNLOAD after setting the address = leave DFU and jump.
      await this.setAddress(base);
      await this.out(DNLOAD, 0, new Uint8Array(0));
      try {
        await this.getStatus();     // triggers manifestation; the device resets
      } catch { /* device disconnects while resetting */ }
      this.log('left DFU mode, application starting');
    }
  }
}

// ---- ide/doom-sim.js
// Runs the DOOM engine compiled to WebAssembly (sim/doom.js) on a canvas.
// The zone heap is split into the same banks, with the same sizes, as the
// firmware build for the selected target, so the simulator runs under the
// real memory budget.

const DOOM_KEYS = {
  ArrowRight: 0xae, ArrowLeft: 0xac, ArrowUp: 0xad, ArrowDown: 0xaf,
  w: 0xad, W: 0xad, s: 0xaf, S: 0xaf, a: 0xac, A: 0xac, d: 0xae, D: 0xae,
  f: 0xa3, F: 0xa3,
  Control: 0xa3, ' ': 0xa2, Escape: 27, Enter: 13, Tab: 9, Backspace: 0x7f,
  Shift: 0x80 + 0x36, Alt: 0x80 + 0x38, ',': 0xa0, '.': 0xa1, '-': 0x2d, '=': 0x3d,
  F1: 0x80 + 0x3b, F2: 0x80 + 0x3c, F3: 0x80 + 0x3d, F4: 0x80 + 0x3e, F5: 0x80 + 0x3f,
  F6: 0x80 + 0x40, F7: 0x80 + 0x41, F8: 0x80 + 0x42, F9: 0x80 + 0x43, F10: 0x80 + 0x44,
  F11: 0x80 + 0x57, Pause: 0xff,
};

function doomKey(e) {
  if (e.key in DOOM_KEYS) return DOOM_KEYS[e.key];
  if (e.key.length === 1) {
    const c = e.key.toLowerCase().charCodeAt(0);
    if (c >= 32 && c < 127) return c;
  }
  return null;
}

// Loads a classic script; unlike fetch() this also works from file://.
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error(`could not load ${src}`));
    document.head.appendChild(s);
  });
}

function fromBase64(b64) {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

let wadPromise = null;
function loadWad() {
  wadPromise = wadPromise || fetch('sim/doom1.wad')
    .then((r) => {
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return r.arrayBuffer();
    })
    .catch(async () => {
      await loadScript('sim/doom1.wad.js');
      return fromBase64(window.FORGE_WAD_B64).buffer;
    });
  return wadPromise;
}

class DoomSim {
  constructor(canvas, { onStatus = () => {}, onExit = () => {} } = {}) {
    this.canvas = canvas;
    this.ctx = canvas.getContext('2d');
    this.image = this.ctx.createImageData(320, 200);
    this.onStatus = onStatus;
    this.onExit = onExit;
    this.mod = null;
    this.running = false;
    this.frames = 0;
  }

  // banks: zone bank sizes in bytes (from the firmware link), in order.
  async start(banks) {
    this.stop();
    if (typeof createDoomModule !== 'function') throw new Error('sim/doom.js did not load');
    const wad = await loadWad();
    let log = '';
    let lastErr = '';
    const mod = await createDoomModule({
      noMainLoop: true,
      print: (t) => { log += t + '\n'; },
      printErr: (t) => {
        log += t + '\n';
        if (t.trim()) lastErr = t.trim();       // I_Error() writes its message to stderr
      },
      onFrame: (ptr) => {
        this.image.data.set(mod.HEAPU8.subarray(ptr, ptr + 320 * 200 * 4));
        this.ctx.putImageData(this.image, 0, 0);
        this.frames++;
      },
    });
    mod.FS.writeFile('/DOOM1.WAD', new Uint8Array(wad));

    const GAP = 16 * 1024;
    let off = 0;
    banks.forEach((size, i) => {
      off += size;
      if (i < banks.length - 1) {
        mod._dg_add_zone_gap(off, GAP);
        off += GAP;
      }
    });
    mod._dg_set_zone_size(off);

    this.mod = mod;
    this.log = () => log;
    this.lastErr = () => lastErr;
    try {
      // Start at E1M1 instead of leaving new players watching an attract demo.
      mod.callMain(['-iwad', '/DOOM1.WAD', '-warp', '1']);
    } catch (e) {
      this.fail(e);
      return;
    }
    this.running = true;
    this.loop();
  }

  loop() {
    const TIC_MS = 1000 / 35;
    let last = performance.now();
    let fpsFrames = 0;
    let fpsTime = last;
    const step = (now) => {
      if (!this.running) return;
      if (now - last >= TIC_MS - 1) {
        last = now;
        try {
          this.mod._doomgeneric_Tick();
        } catch (e) {
          this.fail(e);
          return;
        }
        fpsFrames++;
      }
      if (now - fpsTime > 1000) {
        this.onStatus(`${Math.round((fpsFrames * 1000) / (now - fpsTime))} fps`);
        fpsFrames = 0;
        fpsTime = now;
      }
      this.raf = requestAnimationFrame(step);
    };
    this.raf = requestAnimationFrame(step);
  }

  fail(e) {
    this.running = false;
    const text = this.log ? this.log() : '';
    const reason = (this.lastErr && this.lastErr()) || String(e && e.message ? e.message : e);
    this.onExit(reason, text);
  }

  key(pressed, code) {
    if (this.running && code != null) this.mod._dg_push_key(pressed ? 1 : 0, code);
  }

  stop() {
    this.running = false;
    if (this.raf) cancelAnimationFrame(this.raf);
    this.mod = null;
  }
}

// ---- ide/browser-build.js
// Build the H743 firmware in the browser with a pinned WebAssembly Clang/LLD.
// Compiler assets are lazy-loaded from unpkg and cached by the browser.
const TOOLCHAIN = 'https://unpkg.com/microbit-clang-wasm@21.11.0-alpha.1/gen/bundle.js';
const ENGINE = 'engine/doomgeneric/';
const HAL_DIR = 'firmware/third_party/stm32h7xx_hal/Src/';
const HAL_SOURCES = [
  'hal.c','hal_cortex.c','hal_rcc.c','hal_rcc_ex.c','hal_gpio.c','hal_pwr.c',
  'hal_pwr_ex.c','hal_sd.c','hal_sd_ex.c','ll_sdmmc.c','ll_delayblock.c',
  'hal_spi.c','hal_spi_ex.c','hal_uart.c','hal_uart_ex.c','hal_dma.c',
  'hal_dma_ex.c','hal_mdma.c','hal_flash.c','hal_flash_ex.c',
].map((name) => `${HAL_DIR}stm32h7xx_${name}`);
const BOARD_SOURCES = [
  ...HAL_SOURCES,
  'firmware/targets/h743/board.c',
  'firmware/targets/h743/syscalls.c',
  'firmware/third_party/cmsis/device_h7/system_stm32h7xx.c',
  'firmware/third_party/cmsis/device_h7/startup_stm32h743xx.s',
];
const DOOM_SOURCES = [
  'firmware/targets/h743/dg_stm32.c',
  'firmware/targets/h743/lcd_ili9341.c',
  'firmware/targets/h743/sd_diskio.c',
  'firmware/targets/h743/syscalls_fatfs.c',
  'firmware/third_party/fatfs/ff.c',
  'firmware/third_party/fatfs/ffunicode.c',
];
const COMMON_DEFINES = ['-DSTM32H743xx','-DUSE_HAL_DRIVER'];
const DOOM_DEFINES = [
  '-DCMAP256','-DDG_NO_SCREENBUFFER','-DDG_ZONE_PROVIDER','-DDG_NO_WIPE',
  '-DDG_ZONE_STATIC_TOP','-DDG_STATES_IN_FLASH','-DDOOMGENERIC_RESX=320','-DDOOMGENERIC_RESY=200',
];
const INCLUDES = [
  'firmware/targets/h743', 'firmware/third_party/cmsis/core',
  'firmware/third_party/cmsis/device_h7', 'firmware/third_party/stm32h7xx_hal/Inc',
  'firmware/third_party/fatfs', ENGINE.slice(0, -1),
].map((path) => `-I/src/${path}`);
const CPU = ['-mcpu=cortex-m4','-mthumb','-mfpu=fpv4-sp-d16','-mfloat-abi=softfp'];
let compilerSessionPromise;

function binFromElf(elf) {
  const view = new DataView(elf.buffer, elf.byteOffset, elf.byteLength);
  if (elf[0] !== 0x7f || elf[1] !== 0x45 || elf[2] !== 0x4c || elf[3] !== 0x46 || elf[4] !== 1) {
    throw new Error('Compiler output is not a 32-bit ELF image');
  }
  const phoff = view.getUint32(28, true), phentsize = view.getUint16(42, true), phnum = view.getUint16(44, true);
  const flashStart = 0x08000000, flashEnd = 0x08200000, segments = [];
  for (let i = 0; i < phnum; i++) {
    const p = phoff + i * phentsize;
    if (view.getUint32(p, true) !== 1) continue; // PT_LOAD
    const off = view.getUint32(p + 4, true), addr = view.getUint32(p + 12, true);
    const size = view.getUint32(p + 16, true);
    if (addr >= flashStart && addr + size <= flashEnd && size) segments.push({ off, addr, size });
  }
  if (!segments.length) throw new Error('ELF contains no loadable STM32 flash segment');
  const start = Math.min(...segments.map((s) => s.addr));
  const end = Math.max(...segments.map((s) => s.addr + s.size));
  const image = new Uint8Array(end - start);
  for (const s of segments) image.set(elf.subarray(s.off, s.off + s.size), s.addr - start);
  if (start !== flashStart) throw new Error(`Firmware starts at 0x${start.toString(16)}, expected 0x08000000`);
  return image;
}

function symbolFromElf(elf, target) {
  const view = new DataView(elf.buffer, elf.byteOffset, elf.byteLength);
  const sectionOffset = view.getUint32(32, true), sectionSize = view.getUint16(46, true);
  const sectionCount = view.getUint16(48, true), sections = [];
  for (let i = 0; i < sectionCount; i++) {
    const p = sectionOffset + i * sectionSize;
    sections.push({ type: view.getUint32(p + 4, true), offset: view.getUint32(p + 16, true),
      size: view.getUint32(p + 20, true), link: view.getUint32(p + 24, true), entrySize: view.getUint32(p + 36, true) });
  }
  const decodeName = (table, index) => {
    let end = index;
    while (end < table.length && table[end]) end++;
    return new TextDecoder().decode(table.subarray(index, end));
  };
  for (const section of sections.filter((s) => s.type === 2 && s.entrySize >= 16)) {
    const strings = sections[section.link];
    if (!strings) continue;
    const table = elf.subarray(strings.offset, strings.offset + strings.size);
    for (let p = section.offset; p < section.offset + section.size; p += section.entrySize) {
      const name = decodeName(table, view.getUint32(p, true));
      if (name === target) return view.getUint32(p + 4, true);
    }
  }
  return 0;
}

async function browserH743Build({ project = 'doom', projectConfig, files, source, onLog, toolchainURL = TOOLCHAIN }) {
  if (!/^[a-z0-9-]+$/.test(project)) throw new Error(`Invalid example ID: ${project}`);
  const doom = project === 'doom';
  const log = (message) => onLog?.(message);
  compilerSessionPromise ||= import(toolchainURL).then((toolchain) => toolchain.createSession());
  const session = await compilerSessionPromise;
  const output = (bytes) => { if (bytes) log(new TextDecoder().decode(bytes).trimEnd()); };
  const headers = files.filter((f) => /\.(h|inc|ld)$/.test(f));
  const paths = [...new Set([
    ...BOARD_SOURCES,
    ...(doom ? [...files.filter((f) => f.startsWith(ENGINE) && f.endsWith('.c')), ...DOOM_SOURCES]
      : [`firmware/projects/${project}/main.c`, ...(projectConfig?.sources || [])]),
  ])];
  log(`Preparing ${paths.length} C/assembly units and current editor buffers…`);
  await Promise.all([...new Set([...paths, ...headers])].map(async (path) => {
    const text = await source(path);
    if (text === null) throw new Error(`Missing build source: ${path}`);
    await session.writeFile(`/src/${path}`, text);
  }));
  // The linker wildcard rules place large DOOM arrays by input object basename.
  const objects = [];
  for (let i = 0; i < paths.length; i++) {
    const path = paths[i], engine = path.startsWith(ENGINE);
    const object = `/out/${path.replaceAll('/', '_').replace(/\.(c|s)$/, '')}.o`;
    const args = ['clang', ...CPU, '--sysroot=/usr', '-O2', ...COMMON_DEFINES,
      ...INCLUDES, '-ffunction-sections', '-fdata-sections', '-fno-common',
      ...(engine ? [...DOOM_DEFINES, '-std=gnu99', '-w'] : [...(doom ? DOOM_DEFINES : []), '-std=gnu11', '-Wall']),
      ...(path.endsWith('.s') ? ['-x','assembler-with-cpp'] : []), '-c', `/src/${path}`, '-o', object];
    const code = await session.clang(args, { stdout: output, stderr: output });
    if (code !== 0) throw new Error(`Compile failed: ${path}`);
    objects.push(object);
    if ((i + 1) % 10 === 0 || i + 1 === paths.length) log(`Compiled ${i + 1}/${paths.length} units`);
  }
  const linkLog = [];
  const link = await session.clang(['clang', ...CPU, '--sysroot=/usr', '-nostartfiles',
    '-T/src/firmware/targets/h743/h743.ld', '-Wl,--gc-sections', '-Wl,-Map=/out/firmware.map',
    '-Wl,--print-memory-usage', ...objects, '-lm', '-o', '/out/firmware.elf'], {
    stdout: (b) => { if (b) linkLog.push(new TextDecoder().decode(b)); },
    stderr: (b) => { if (b) linkLog.push(new TextDecoder().decode(b)); },
  });
  linkLog.join('').split('\n').filter(Boolean).forEach(log);
  if (link !== 0) throw new Error('H743 link failed. Review the compiler and linker output above.');
  const elf = await session.readFile('/out/firmware.elf');
  const binary = binFromElf(elf);
  const symbol = (name) => symbolFromElf(elf, name);
  const zoneBanks = doom
    ? [['__zone0_start','__zone0_end'],['__zone1_start','__zone1_end'],['__zone2_start','__zone2_end']]
      .map(([a, b]) => symbol(b) - symbol(a))
    : [];
  return {
    ok: true, binary: (() => {
      let encoded = '';
      for (let i = 0; i < binary.length; i += 0x8000) encoded += String.fromCharCode(...binary.subarray(i, i + 0x8000));
      return btoa(encoded);
    })(), binarySize: binary.length,
    source: 'browser WebAssembly Clang build', zone: zoneBanks.reduce((a, b) => a + b, 0), zoneBanks,
    memory: [...linkLog.join('').matchAll(/^\s*(ITCM|FLASH|DTCM|AXI|SRAM123|SRAM4):\s*(\d+)\s*(B|KB|MB|GB)\s+(\d+)\s*(B|KB|MB|GB)\s+([\d.]+)%\s*$/gm)]
      .map((m) => {
        const bytes = (amount, unit) => Number(amount) * ({ B: 1, KB: 1024, MB: 1048576, GB: 1073741824 }[unit]);
        const used = bytes(m[2], m[3]), size = bytes(m[4], m[5]);
        return { region: m[1], used, size, overflow: Math.max(0, used - size) };
      }),
    log: linkLog.join(''),
  };
}

// ---- ide/app.js
// STM32 Forge IDE: editor, browser/local builds, memory report,
// DOOM emulator, and flashing / serial console over Web Serial and WebUSB.

const $ = (id) => document.getElementById(id);
const TARGETS = {
  h743: { name: 'STM32H743IITx', flash: 2048 * 1024, ram: 1024 * 1024, dfu: true },
  bluepill: { name: 'STM32F103C8T6 Blue Pill', flash: 64 * 1024, ram: 20 * 1024, dfu: false },
};
const DOOM_MIN_ZONE = 704 * 1024;   // smallest zone that ran every demo (tests/sim_headless.mjs)

const state = {
  server: false,
  manifest: null,
  builds: {},          // "target-project" -> build result (from server or manifest)
  files: [],
  projects: [],
  projectGroups: [],
  open: new Map(),     // path -> { doc, saved }
  active: null,
  port: null,          // Web Serial port shared by console and UART flashing
  console: null,       // { reader, writer } while the console is open
};
const DRAFT_KEY = 'stm32-forge-drafts-v1';
function drafts() {
  try { return JSON.parse(localStorage.getItem(DRAFT_KEY) || '{}'); }
  catch { return {}; }
}

const combo = () => `${$('target').value}-${$('project').value}`;
const kb = (n) => (n >= 1024 * 1024 ? `${(n / 1048576).toFixed(2)} MB` : `${(n / 1024).toFixed(n < 10240 ? 1 : 0)} KB`);

// ------------------------------------------------------------ terminals --
function term(name, text, cls) {
  const el = $(`term-${name}`);
  const span = document.createElement('span');
  if (cls) span.className = cls;
  span.textContent = text;
  el.appendChild(span);
  if (el.childNodes.length > 4000) el.removeChild(el.firstChild);
  el.scrollTop = el.scrollHeight;
}
const line = (name, text, cls) => term(name, text + '\n', cls);

function showTerm(name) {
  document.querySelectorAll('.bottom-tabs [data-term]').forEach((b) => b.classList.toggle('active', b.dataset.term === name));
  document.querySelectorAll('.term').forEach((t) => t.classList.toggle('active', t.id === `term-${name}`));
  $('serial-form').hidden = name !== 'serial';
}
document.querySelectorAll('.bottom-tabs [data-term]').forEach((b) => b.addEventListener('click', () => showTerm(b.dataset.term)));
$('btn-clear').addEventListener('click', () => {
  const t = document.querySelector('.term.active');
  if (t) t.textContent = '';
});

// ------------------------------------------------------------ server --
async function detectServer() {
  const s = $('server-status');
  try {
    const r = await fetch('api/status', { cache: 'no-store' });
    if (!r.ok) throw new Error();
    const st = await r.json();
    state.server = true;
    s.innerHTML = st.toolchain
      ? `<span class="dot ok"></span><span>build server · ${st.toolchain.replace(/^arm-none-eabi-gcc /, 'gcc ')}</span>`
      : '<span class="dot warn"></span><span>build server · toolchain not found (set ARM_GCC_PATH)</span>';
  } catch {
    state.server = false;
    s.innerHTML = '<span class="dot ok"></span><span>static IDE · browser build · local drafts</span>';
    s.title = 'Source edits and firmware builds run in this browser. Flashing uses Web Serial or WebUSB.';
  }
  $('btn-build').disabled = false;
  $('btn-build').title = state.server ? 'Build (Ctrl+B)' : 'Build H743 firmware in this browser (Ctrl+B)';
}

// Prebuilt manifest + images as a script (fallback when fetch is blocked).
async function prebuiltScript() {
  if (!window.FORGE_PREBUILT) await loadScript('firmware/prebuilt/prebuilt.js');
  return window.FORGE_PREBUILT;
}

async function loadManifest() {
  try {
    const r = await fetch('firmware/prebuilt/manifest.json', { cache: 'no-store' });
    state.manifest = await r.json();
  } catch {
    try {
      state.manifest = (await prebuiltScript()).manifest;
    } catch {
      state.manifest = { builds: {} };
    }
  }
}

// ------------------------------------------------------------ files --
async function loadTree() {
  try {
    if (state.server) {
      state.files = (await (await fetch('api/tree')).json()).files;
    } else {
      state.files = (await (await fetch('ide/files.json')).json()).files;
    }
  } catch {
    try {
      await loadScript('ide/files.js');
      state.files = window.FORGE_FILES.files;
    } catch {
      state.files = [];
    }
  }
  renderTree();
}

async function loadProjectCatalog() {
  let groups = [];
  const fallback = [
    { id: 'doom', name: 'DOOM', group: 'games', description: 'Playable DOOM on the H743.', entry: 'firmware/targets/h743/dg_stm32.c', targets: ['h743'], emulator: true },
    { id: 'blinky', name: 'Blinky', group: 'basics', description: 'Blink PC13 and report over USART1.', entry: 'firmware/projects/blinky/main.c', targets: ['h743', 'bluepill'] },
  ];
  try {
    const response = await fetch('firmware/projects/catalog.json', { cache: 'no-store' });
    if (!response.ok) throw new Error('catalog unavailable');
    const catalog = await response.json();
    state.projects = catalog.projects;
    groups = catalog.groups;
  } catch {
    state.projects = fallback;
    groups = [{ id: 'games', name: 'Games' }, { id: 'basics', name: 'Getting started' }];
  }
  state.projectGroups = groups;
  const select = $('project');
  select.textContent = '';
  for (const group of new Set(state.projects.map((project) => project.group))) {
    const optgroup = document.createElement('optgroup');
    optgroup.label = groups.find((item) => item.id === group)?.name || group;
    for (const project of state.projects.filter((item) => item.group === group)) {
      const option = document.createElement('option');
      option.value = project.id;
      option.textContent = project.name;
      option.dataset.targets = project.targets.join(',');
      optgroup.appendChild(option);
    }
    select.appendChild(optgroup);
  }
  refreshProjectAvailability();
}

function projectInfo() {
  return state.projects.find((project) => project.id === $('project').value) || state.projects[0];
}

function refreshProjectAvailability() {
  const target = $('target').value;
  for (const option of $('project').options) {
    option.disabled = !option.dataset.targets.split(',').includes(target);
  }
  if ($('project').selectedOptions[0]?.disabled) {
    const next = [...$('project').options].find((option) => !option.disabled);
    if (next) $('project').value = next.value;
  }
}

function renderTree() {
  const root = {};
  for (const f of state.files) {
    const parts = f.split('/');
    let node = root;
    parts.slice(0, -1).forEach((p) => { node = node[p] = node[p] || {}; });
    node[parts.at(-1)] = f;
  }
  const tree = $('tree');
  tree.textContent = '';
  const collapsedByDefault = new Set(['doomgeneric']);
  const walk = (node, parent, depth) => {
    const entries = Object.entries(node).sort(([a, av], [b, bv]) =>
      (typeof av === 'string') - (typeof bv === 'string') || a.localeCompare(b));
    for (const [name, v] of entries) {
      if (typeof v === 'string') {
        const el = document.createElement('div');
        el.className = 'file';
        el.style.paddingLeft = `${14 + depth * 12}px`;
        el.textContent = name;
        el.dataset.path = v;
        el.addEventListener('click', () => openFile(v));
        parent.appendChild(el);
      } else {
        const d = document.createElement('div');
        d.className = 'dir' + (collapsedByDefault.has(name) ? ' collapsed' : '');
        d.style.paddingLeft = `${6 + depth * 12}px`;
        d.textContent = name;
        const kids = document.createElement('div');
        kids.className = 'children';
        d.addEventListener('click', () => d.classList.toggle('collapsed'));
        parent.append(d, kids);
        walk(v, kids, depth + 1);
      }
    }
  };
  walk(root, tree, 0);
  if (!state.files.length) tree.innerHTML = '<div class="note">No source listing available.</div>';
  highlightTree();
}

function highlightTree() {
  document.querySelectorAll('.tree .file').forEach((el) => el.classList.toggle('active', el.dataset.path === state.active));
}

let cm = null;
function editor() {
  if (!cm) {
    $('editor-empty').remove();
    cm = CodeMirror($('editor-body'), {
      lineNumbers: true, matchBrackets: true, styleActiveLine: true, indentUnit: 4,
      readOnly: false,
    });
    cm.on('change', () => {
      const f = state.open.get(state.active);
      if (f) renderTabs();
    });
  }
  return cm;
}

function modeFor(path) {
  if (/\.s$/i.test(path)) return { name: 'gas', architecture: 'ARM' };
  if (/Makefile|\.ld$/.test(path)) return 'text/plain';
  return 'text/x-csrc';
}

async function openFile(path) {
  if (!state.open.has(path)) {
    let text;
    try {
      if (state.server) {
        text = (await (await fetch(`api/file?path=${encodeURIComponent(path)}`)).json()).content;
      } else {
        const r = await fetch(path);
        if (!r.ok) throw new Error(r.status);
        text = await r.text();
      }
    } catch (e) {
      line('build', location.protocol === 'file:'
        ? `${path}: browsers block reading project files from file://. Open the online demo or run node server/forge_server.mjs in a local checkout.`
        : `could not open ${path}: ${e.message}`, 'err');
      return;
    }
    if (!state.server) text = drafts()[path] ?? text;
    const doc = CodeMirror.Doc(text, modeFor(path));
    state.open.set(path, { doc, saved: doc.changeGeneration() });
  }
  state.active = path;
  editor().swapDoc(state.open.get(path).doc);
  renderTabs();
  highlightTree();
}

function renderTabs() {
  const tabs = $('tabs');
  tabs.textContent = '';
  for (const [path, f] of state.open) {
    const t = document.createElement('div');
    t.className = 'editor-tab' + (path === state.active ? ' active' : '') +
      (f.doc.isClean(f.saved) ? '' : ' dirty');
    t.title = path;
    t.innerHTML = `<span class="name"></span><span class="x" title="Close">×</span>`;
    t.querySelector('.name').textContent = path.split('/').pop();
    t.addEventListener('click', (e) => {
      if (e.target.classList.contains('x')) return closeFile(path);
      openFile(path);
    });
    tabs.appendChild(t);
  }
  const f = state.open.get(state.active);
  $('btn-save').disabled = !f || f.doc.isClean(f.saved);
}

function closeFile(path) {
  const f = state.open.get(path);
  if (f && !f.doc.isClean(f.saved) && !confirm(`Discard unsaved changes to ${path}?`)) return;
  state.open.delete(path);
  if (state.active === path) {
    const next = [...state.open.keys()].pop();
    if (next) openFile(next);
    else {
      state.active = null;
      cm.swapDoc(CodeMirror.Doc(''));
    }
  }
  renderTabs();
}

async function saveAll() {
  const local = drafts();
  let saved = 0;
  for (const [path, f] of state.open) {
    if (f.doc.isClean(f.saved)) continue;
    if (state.server) {
      const r = await fetch(`api/file?path=${encodeURIComponent(path)}`, { method: 'PUT', body: f.doc.getValue() });
      if (!r.ok) {
        line('build', `save failed: ${path}`, 'err');
        continue;
      }
    } else {
      local[path] = f.doc.getValue();
    }
    f.saved = f.doc.changeGeneration();
    saved++;
  }
  if (!state.server && saved) {
    try {
      localStorage.setItem(DRAFT_KEY, JSON.stringify(local));
      line('build', `saved ${saved} browser draft${saved === 1 ? '' : 's'} on this device`, 'ok');
    } catch (e) {
      line('build', `could not save browser drafts: ${e.message}`, 'err');
      return;
    }
  } else if (state.server && saved) line('build', `saved ${saved} file${saved === 1 ? '' : 's'} to the checkout`, 'dim');
  renderTabs();
}
$('btn-save').addEventListener('click', saveAll);

// ------------------------------------------------------------ build --
async function build() {
  if (!state.server) {
    showTerm('build');
    if ($('target').value !== 'h743') {
      line('build', 'Browser firmware builds currently target the STM32H743. Select that board to build here.', 'warn');
      return;
    }
    await buildInBrowser();
    return;
  }
  await saveAll();
  const [target, project] = [$('target').value, $('project').value];
  showTerm('build');
  $('term-build').textContent = '';
  line('build', `$ make TARGET=${target} PROJECT=${project}`, 'dim');
  $('btn-build').disabled = true;
  $('btn-build').textContent = 'Building…';
  const t0 = performance.now();
  try {
    const r = await (await fetch('api/build', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ target, project }),
    })).json();
    for (const l of r.log.split('\n')) {
      const cls = /error|overflowed|will not fit/i.test(l) ? 'err' : /warning/i.test(l) ? 'warn'
        : /^(CC|AS|LD) /.test(l) ? 'dim' : '';
      line('build', l, cls);
    }
    const secs = ((performance.now() - t0) / 1000).toFixed(1);
    if (r.ok) {
      line('build', `Build succeeded in ${secs}s: firmware.bin ${kb(r.binarySize)}` +
        (r.zone ? `, DOOM zone heap ${kb(r.zone)}` : ''), 'ok');
    } else {
      line('build', `Build FAILED in ${secs}s`, 'err');
    }
    r.source = 'this build';
    state.builds[`${target}-${project}`] = r;
    renderMemory();
    updateEmulator();
  } catch (e) {
    line('build', `build request failed: ${e.message}`, 'err');
  } finally {
    $('btn-build').disabled = false;
    $('btn-build').textContent = 'Build';
  }
}

async function buildInBrowser() {
  const [target, project] = [$('target').value, $('project').value];
  const selected = projectInfo();
  showTerm('build');
  $('term-build').textContent = '';
  if (!selected || !selected.targets.includes(target)) {
    line('build', 'Select an example supported by the current board.', 'warn');
    return;
  }
  $('btn-build').disabled = true;
  $('btn-build').textContent = 'Loading compiler…';
  const started = performance.now();
  try {
    const source = async (path) => {
      const open = state.open.get(path);
      if (open) return open.doc.getValue();
      const response = await fetch(path);
      return response.ok ? response.text() : null;
    };
    line('build', 'Loading pinned ARM compiler and runtime (~98 MB, cached by browser)…', 'dim');
    const result = await browserH743Build({
      project,
      projectConfig: selected,
      files: state.files,
      source,
      onLog: (message) => {
        line('build', message, /error|overflow/i.test(message) ? 'err' : /compiled|region|used size/i.test(message) ? 'dim' : '');
        $('btn-build').textContent = 'Compiling…';
      },
    });
    result.source = 'browser WebAssembly Clang build';
    state.builds[`${target}-${project}`] = result;
    const secs = ((performance.now() - started) / 1000).toFixed(1);
    line('build', `Build succeeded in ${secs}s: firmware.bin ${kb(result.binarySize)}` +
      (project === 'doom' ? `, DOOM zone heap ${kb(result.zone)}` : ''), 'ok');
    renderMemory();
    updateEmulator();
  } catch (error) {
    line('build', `Build failed: ${error.message}`, 'err');
  } finally {
    $('btn-build').disabled = false;
    $('btn-build').textContent = 'Build';
  }
}
$('btn-build').addEventListener('click', build);

function currentBuild() {
  return state.builds[combo()] || (state.manifest && state.manifest.builds[combo()] &&
    { ...state.manifest.builds[combo()], source: 'prebuilt' });
}

// ------------------------------------------------------------ memory --
function renderMemory() {
  const b = currentBuild();
  const t = TARGETS[$('target').value];
  const el = $('memory');
  $('mem-source').textContent = b ? `linker report · ${b.source}` : '';
  if (!b || !b.memory || !b.memory.length) {
    el.innerHTML = `<div class="note">No build yet for this target. ${state.server ? 'Press Build.' : ''}</div>`;
    return;
  }
  const flash = b.memory.filter((m) => m.region === 'FLASH');
  const ram = b.memory.filter((m) => m.region !== 'FLASH');
  const sum = (list, k) => list.reduce((a, m) => a + m[k], 0);
  const flashUsed = sum(flash, 'used');
  const ramStatic = sum(ram, 'used');
  const zone = b.zone || 0;
  const ramSize = sum(ram, 'size');

  const bar = (parts, total, over) => `<div class="bar${over ? ' over' : ''}">${parts
    .map(([cls, v]) => `<span class="${cls}" style="width:${Math.min(100, (v / total) * 100).toFixed(2)}%"></span>`).join('')}</div>`;

  let html = `
    <div class="mem-group">
      <div class="mem-title"><span>Flash</span><span class="big mono">${kb(flashUsed)} / ${kb(t.flash)}</span></div>
      ${bar([['flash', flashUsed]], t.flash, flashUsed > t.flash)}
    </div>
    <div class="mem-group">
      <div class="mem-title"><span>RAM</span><span class="big mono">${kb(ramStatic + zone)} / ${kb(ramSize)}</span></div>
      ${bar([['ram', ramStatic], ['zone', zone]], ramSize, ramStatic > ramSize)}
      <div class="legend"><span><i style="background:var(--bar-ram)"></i>static data, heap, stack ${kb(ramStatic)}</span>
      ${zone ? `<span><i style="background:var(--bar-zone)"></i>DOOM zone heap ${kb(zone)}</span>` : ''}</div>
    </div>
    <div class="mem-regions">`;
  for (const m of b.memory) {
    const over = m.overflow > 0 || m.used > m.size;
    html += `<span class="name">${m.region}</span>${bar([[m.region === 'FLASH' ? 'flash' : 'ram', m.used]], m.size, over)}
      <span class="num${over ? ' over' : ''}">${kb(m.used)} / ${kb(m.size)}</span>`;
  }
  html += '</div>';

  if (!b.ok) {
    const overs = b.memory.filter((m) => m.overflow).map((m) => `${m.region} overflowed by ${kb(m.overflow)}`);
    html += `<div class="verdict bad">Does not fit on the ${t.name}: ${overs.join(', ') || 'link failed'}.</div>`;
  } else if ($('project').value === 'doom') {
    html += `<div class="verdict ok">Fits. DOOM gets a ${kb(zone)} zone heap (needs ≥ ${kb(DOOM_MIN_ZONE)}).</div>`;
  } else {
    html += `<div class="verdict ok">Fits: ${kb(flashUsed)} flash, ${kb(ramStatic)} RAM.</div>`;
  }
  el.innerHTML = html;
}

// ------------------------------------------------------------ emulator --
const sim = new DoomSim($('screen'), {
  onStatus: (s) => { $('emu-fps').textContent = s; },
  onExit: (reason) => {
    $('btn-run').disabled = false;
    $('btn-stop').disabled = true;
    $('emu-fps').textContent = '';
    overlay(`<strong>DOOM stopped</strong><span class="mono">${escapeHtml(reason)}</span>`, true);
  },
});

function escapeHtml(s) {
  return String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}

function overlay(html, bad) {
  const o = $('emu-overlay');
  o.hidden = !html;
  o.className = 'overlay' + (bad ? ' bad' : '');
  o.innerHTML = html || '';
}

function updateEmulator() {
  if (sim.running) return;
  const target = $('target').value;
  const project = $('project').value;
  const b = currentBuild();
  const example = projectInfo();
  $('btn-run').disabled = false;
  if (project !== 'doom') {
    overlay(`<strong>${escapeHtml(example?.name || 'Firmware example')}</strong><span>${escapeHtml(example?.description || 'Build and flash this board example to try it.')}</span><span>Build this example, flash the image, then use the serial monitor or connected hardware as described.</span>`);
    $('btn-run').disabled = true;
    $('emu-note').textContent = '';
    return;
  }
  if (target === 'bluepill') {
    const ram = b && b.memory ? b.memory.find((m) => m.region === 'RAM') : null;
    overlay(`<strong>DOOM does not fit on a Blue Pill</strong>
      <span>The linker needs ${ram ? kb(ram.used) : 'about 1 MB'} of RAM; the STM32F103C8 has 20 KB.
      DOOM's heap alone needs at least ${kb(DOOM_MIN_ZONE)}.</span>
      <span>Press Run to start the engine with a 20 KB heap anyway and watch it fail.</span>`, true);
    $('emu-note').textContent = 'Blue Pill budget: 20 KB of RAM in total.';
    return;
  }
  const banks = b && b.zoneBanks;
  overlay(`<strong>Real DOOM, same engine source as the firmware</strong>
    <span>Heap limited to the H743 build: ${banks ? banks.map(kb).join(' + ') : '?'} across DTCM, AXI SRAM and SRAM1-3.</span>
    <span>Press Run, then click the screen for keyboard input.</span>`);
  $('emu-note').textContent = banks ? `Zone heap: ${kb(banks.reduce((a, x) => a + x, 0))} in ${banks.length} banks.` : '';
}

$('btn-run').addEventListener('click', async () => {
  const target = $('target').value;
  const b = currentBuild();
  let banks;
  if (target === 'bluepill') banks = [20 * 1024];
  else if (b && b.zoneBanks) banks = b.zoneBanks;
  else banks = [12336, 416672, 294912];
  $('btn-run').disabled = true;
  overlay('<strong>Loading DOOM1.WAD…</strong>');
  try {
    await sim.start(banks);
    if (sim.running) {
      overlay('');
      $('btn-stop').disabled = false;
      $('screen').focus();
    }
  } catch (e) {
    $('btn-run').disabled = false;
    overlay(`<strong>Could not start</strong><span>${escapeHtml(e.message)}</span>`, true);
  }
});
$('btn-stop').addEventListener('click', () => {
  sim.stop();
  $('btn-stop').disabled = true;
  $('emu-fps').textContent = '';
  updateEmulator();
});

function onKey(pressed, e) {
  const code = doomKey(e);
  if (code == null) return;
  e.preventDefault();
  sim.key(pressed, code);
  if ($('pad-hw').checked && state.console) {
    state.console.writer.write(Uint8Array.of(pressed ? 0xf0 : 0xf1, code)).catch(() => {});
  }
}
$('screen').addEventListener('keydown', (e) => { if (!e.repeat) onKey(true, e); else e.preventDefault(); });
$('screen').addEventListener('keyup', (e) => onKey(false, e));
$('screen').addEventListener('click', () => $('screen').focus());

// ------------------------------------------------------------ serial console --
async function openConsole() {
  if (!('serial' in navigator)) {
    line('serial', 'Web Serial is not available in this browser (use Chrome or Edge).', 'err');
    showTerm('serial');
    return;
  }
  try {
    state.port = state.port || await navigator.serial.requestPort();
    await state.port.open({ baudRate: 115200 });
  } catch (e) {
    line('serial', `could not open port: ${e.message}`, 'err');
    showTerm('serial');
    return;
  }
  const reader = state.port.readable.getReader();
  const writer = state.port.writable.getWriter();
  state.console = { reader, writer };
  $('btn-serial').textContent = 'Disconnect serial';
  showTerm('serial');
  line('serial', '— connected at 115200 8N1 —', 'ok');
  const dec = new TextDecoder();
  (async () => {
    try {
      for (;;) {
        const { value, done } = await reader.read();
        if (done) break;
        term('serial', dec.decode(value, { stream: true }).replace(/\r/g, ''));
      }
    } catch (e) {
      line('serial', `— ${e.message} —`, 'warn');
    }
  })();
}

async function closeConsole() {
  if (!state.console) return;
  const { reader, writer } = state.console;
  state.console = null;
  try { await reader.cancel(); } catch { /* already closed */ }
  reader.releaseLock();
  writer.releaseLock();
  try { await state.port.close(); } catch { /* ignore */ }
  $('btn-serial').textContent = 'Connect serial';
  line('serial', '— disconnected —', 'dim');
}

$('btn-serial').addEventListener('click', () => (state.console ? closeConsole() : openConsole()));
$('serial-form').addEventListener('submit', (e) => {
  e.preventDefault();
  if (!state.console) return;
  const text = $('serial-line').value + '\r';
  state.console.writer.write(new TextEncoder().encode(text));
  $('serial-line').value = '';
});

// ------------------------------------------------------------ flashing --
async function firmwareImage() {
  const b = state.builds[combo()];
  if (b && b.ok && b.binary) {
    return { bytes: fromBase64(b.binary), from: 'your latest build' };
  }
  const from = `prebuilt firmware/prebuilt/${combo()}.bin`;
  try {
    const r = await fetch(`firmware/prebuilt/${combo()}.bin`, { cache: 'no-store' });
    if (r.ok) return { bytes: new Uint8Array(await r.arrayBuffer()), from };
  } catch {
    const pre = await prebuiltScript().catch(() => null);
    const b64 = pre && pre.images[combo()];
    if (b64) return { bytes: fromBase64(b64), from };
  }
  return null;
}

function progress(phase, done, total) {
  const p = $('flash-progress');
  p.hidden = false;
  const pct = phase === 'erase' ? 5 * (done / total) : phase === 'write' ? 5 + 75 * (done / total) : 80 + 20 * (done / total);
  p.firstElementChild.style.width = `${pct.toFixed(1)}%`;
}

$('btn-flash').addEventListener('click', async () => {
  const t = TARGETS[$('target').value];
  const b = currentBuild();
  if (b && b.ok === false) {
    showTerm('flash');
    line('flash', `${combo()} does not fit on the ${t.name}; nothing to flash.`, 'err');
    return;
  }
  const img = await firmwareImage();
  if (!img) {
    showTerm('flash');
    line('flash', 'No firmware image: build first.', 'err');
    return;
  }
  if (!img.bytes.length || img.bytes.length > t.flash) {
    showTerm('flash');
    line('flash', `Firmware image is ${kb(img.bytes.length)}; ${t.name} has ${kb(t.flash)} flash.`, 'err');
    return;
  }
  $('fd-what').textContent = `${$('project').selectedOptions[0].text} → ${t.name}`;
  $('fd-image').textContent = `${kb(img.bytes.length)} from ${img.from}`;
  $('m-dfu').classList.toggle('disabled', !t.dfu);
  if (!t.dfu) $('m-uart').querySelector('input').checked = true;
  const support = [];
  if (!('serial' in navigator)) support.push('Web Serial is not available in this browser');
  if (!('usb' in navigator)) support.push('WebUSB is not available in this browser');
  $('fd-support').textContent = support.length ? `${support.join('; ')}. Use Chrome or Edge.` : '';
  $('flash-dialog').returnValue = '';
  $('flash-dialog').showModal();
  $('flash-dialog').onclose = () => {
    if ($('flash-dialog').returnValue === 'go') {
      const method = new FormData($('flash-dialog').querySelector('form')).get('method');
      const file = $('custom-firmware').files[0];
      if (!file) {
        flash(method, img.bytes);
        return;
      }
      file.arrayBuffer().then((buffer) => {
        const bytes = new Uint8Array(buffer);
        if (!bytes.length || bytes.length > t.flash) {
          showTerm('flash');
          line('flash', `Firmware image is ${kb(bytes.length)}; ${t.name} has ${kb(t.flash)} flash.`, 'err');
          return;
        }
        flash(method, bytes);
      }).catch((e) => {
        showTerm('flash');
        line('flash', `Could not read firmware image: ${e.message}`, 'err');
      });
    }
  };
});

$('custom-firmware').addEventListener('change', () => {
  const file = $('custom-firmware').files[0];
  if (file) $('fd-image').textContent = `${kb(file.size)} from rebuilt image ${file.name}`;
});

async function flash(method, image) {
  showTerm('flash');
  const log = (s) => line('flash', s);
  const t0 = performance.now();
  try {
    if (method === 'dfu') {
      const dev = await navigator.usb.requestDevice({ filters: DFU_FILTERS });
      const dfu = new DfuSe(dev, log);
      await dfu.open();
      await dfu.flash(image, { onProgress: progress });
    } else {
      await closeConsole();
      state.port = state.port || await navigator.serial.requestPort();
      const transport = await webSerialTransport(state.port);
      try {
        const bl = new An3155(transport, log);
        await bl.connect();
        await bl.flash(image, { onProgress: progress });
      } finally {
        await transport.close();
      }
    }
    line('flash', `Flashed and verified ${kb(image.length)} in ${((performance.now() - t0) / 1000).toFixed(1)}s. ` +
      'Set BOOT0 low and reset if the board does not start by itself.', 'ok');
  } catch (e) {
    line('flash', `Flash failed: ${e.message}`, 'err');
    if (method === 'uart') line('flash', 'Check: BOOT0 high, board reset after that, TX→PA10 / RX→PA9, adapter at 3.3 V.', 'dim');
  } finally {
    setTimeout(() => { $('flash-progress').hidden = true; }, 1500);
  }
}

// ------------------------------------------------------------ wiring --
function onSelection() {
  refreshProjectAvailability();
  renderMemory();
  if (sim.running) sim.stop(), $('btn-stop').disabled = true;
  updateEmulator();
  const project = projectInfo();
  const main = project?.entry || 'firmware/projects/blinky/main.c';
  $('example-name').textContent = project?.name || 'Firmware example';
  $('example-description').textContent = project?.description || '';
  $('example-targets').textContent = project?.targets.map((target) => target.toUpperCase()).join(' · ') || '';
  if (state.files.includes(main)) openFile(main);
}
$('target').addEventListener('change', onSelection);
$('project').addEventListener('change', onSelection);

document.addEventListener('keydown', (e) => {
  if ((e.ctrlKey || e.metaKey) && e.key === 's') { e.preventDefault(); saveAll(); }
  if ((e.ctrlKey || e.metaKey) && e.key === 'b') { e.preventDefault(); build(); }
});
window.addEventListener('beforeunload', (e) => {
  if ([...state.open.values()].some((f) => !f.doc.isClean(f.saved))) e.preventDefault();
});

(async () => {
  await Promise.all([detectServer(), loadManifest(), loadProjectCatalog()]);
  await loadTree();
  line('build', state.server
    ? 'Ready. Build runs arm-none-eabi-gcc on this machine (Ctrl+B).'
    : 'Static IDE ready: edit sources, build H743 firmware in the browser, and flash with Web Serial or WebUSB. Browser drafts stay on this device.', 'dim');
  onSelection();
})();

const brightnessInput = $('screen-brightness');
const brightnessValue = $('screen-brightness-value');
function setGameBrightness(value) {
  const percent = Math.max(100, Math.min(175, Number(value) || 140));
  $('screen').style.filter = `brightness(${percent / 100}) saturate(1.08)`;
  brightnessInput.value = String(percent);
  brightnessValue.value = `${percent}%`;
}
brightnessInput.addEventListener('input', () => {
  setGameBrightness(brightnessInput.value);
  localStorage.setItem('stm32-forge-game-brightness', brightnessInput.value);
});
setGameBrightness(localStorage.getItem('stm32-forge-game-brightness') || brightnessInput.value);

})();
