import test from 'node:test';
import assert from 'node:assert/strict';
import { chrome, withStaticIde } from './chrome_ide.mjs';

test('static IDE runs C source on virtual HAL and search opens real source matches', { skip: !chrome }, async () => {
  await withStaticIde(async ({ send, evaluate, waitFor, errors, requests }) => {
    await waitFor(`document.fonts.status === 'loaded' && typeof CodeMirror === 'function'`);
    const external = requests.filter((url) => !/^(http:\/\/127\.0\.0\.1:\d+\/|data:|blob:)/.test(url));
    assert.deepEqual(external, [], 'the site is self-contained: nothing is loaded from other hosts');
    await evaluate(`(() => { const p=document.querySelector('#project'); p.value='button-led'; p.dispatchEvent(new Event('change',{bubbles:true})); return true; })()`);
    await waitFor(`document.querySelector('#preview-log')?.textContent.includes('press PE4')`);
    await evaluate(`document.querySelector('#preview-button').click()`);
    await waitFor(`document.querySelector('#preview-log')?.textContent.includes('button press')`);
    assert.equal(await evaluate(`document.querySelector('#preview-led').classList.contains('on')`), true);
    await evaluate(`(() => { document.querySelector('#source-search-query').value='HAL_GPIO_(ReadPin|TogglePin)'; document.querySelector('#source-search-regex').checked=true; document.querySelector('#source-search-form').requestSubmit(); return true; })()`);
    await waitFor(`document.querySelector('#source-search-results')?.textContent.includes('firmware/projects/button-led/main.c:')`);
    await evaluate(`([...document.querySelectorAll('.search-result')].find(x=>x.textContent.includes('firmware/projects/button-led/main.c:'))).click()`);
    await waitFor(`document.querySelector('.editor-tab.active')?.title === 'firmware/projects/button-led/main.c'`);
    assert.equal(await evaluate(`document.querySelector('#btn-save') === null`), true);
    await evaluate(`(() => { const cm=document.querySelector('.CodeMirror').CodeMirror; cm.setValue(cm.getValue()+'\\n// autosave verification\\n'); return true; })()`);
    await waitFor(`JSON.parse(localStorage.getItem('stm32-forge-drafts-v1')||'{}')['firmware/projects/button-led/main.c']?.includes('autosave verification')`);
    await waitFor(`document.querySelector('#modified-warning')?.textContent.includes('firmware/projects/button-led/main.c')`);
    await evaluate(`document.querySelector('#btn-reset-samples').click()`);
    assert.equal(await evaluate(`document.querySelector('#reset-dialog').open`), true);
    assert.equal(await evaluate(`document.querySelector('#reset-file-list').textContent.includes('firmware/projects/button-led/main.c')`), true);
    await evaluate(`document.querySelector('#confirm-reset-samples').click()`);
    await waitFor(`document.querySelector('#modified-warning').hidden`);
    assert.equal(await evaluate(`JSON.parse(localStorage.getItem('stm32-forge-drafts-v1')||'{}')['firmware/projects/button-led/main.c']`), undefined);
    const beforeDockedDrag = await evaluate(`document.querySelector('.files').getBoundingClientRect().left`);
    const headerPoint = await evaluate(`(() => { const r=document.querySelector('.files .panel-head').getBoundingClientRect(); return {x:r.left+Math.min(20,r.width/2),y:r.top+r.height/2}; })()`);
    await send('Input.dispatchMouseEvent', { type:'mousePressed', x:headerPoint.x, y:headerPoint.y, button:'left', buttons:1 });
    await send('Input.dispatchMouseEvent', { type:'mouseMoved', x:headerPoint.x+45, y:headerPoint.y+28, button:'left', buttons:1 });
    await send('Input.dispatchMouseEvent', { type:'mouseReleased', x:headerPoint.x+45, y:headerPoint.y+28, button:'left', buttons:0 });
    assert.equal(await evaluate(`document.querySelector('.files').classList.contains('floating')`), true);
    assert.equal(await evaluate(`Math.abs(parseInt(document.querySelector('.files').style.left,10) - (${beforeDockedDrag} + 45)) < 2`), true);
    assert.equal(await evaluate(`getComputedStyle(document.querySelector('.files')).resize`), 'both');
    await evaluate(`document.querySelector('.files .pane-toggle').click()`);
    assert.equal(await evaluate(`document.querySelector('.files').classList.contains('floating')`), false);
    await evaluate(`document.querySelector('.editor .pane-toggle').click()`);
    assert.equal(await evaluate(`document.querySelector('.editor').classList.contains('floating')`), true);
    assert.equal(await evaluate(`document.querySelector('.editor-tab.active')?.title`), 'firmware/projects/button-led/main.c');
    await evaluate(`document.querySelector('.editor .pane-toggle').click()`);
    assert.equal(await evaluate(`document.querySelector('.bottom .pane-toggle')?.textContent`), 'Float');
    await evaluate(`(() => { const p=document.querySelector('#project'); p.value='freertos'; p.dispatchEvent(new Event('change',{bubbles:true})); return true; })()`);
    await waitFor(`document.querySelector('#preview-log')?.textContent.includes('[LED task] heartbeat') && document.querySelector('#preview-log')?.textContent.includes('[monitor task] tick')`, 10000);
    await waitFor(`document.querySelector('#preview-rtos')?.hidden === false && [...document.querySelectorAll('.rtos-task')].length === 2`);
    assert.equal(await evaluate(`[...document.querySelectorAll('.rtos-task')].every(row => ['LED','Monitor'].includes(row.dataset.taskName))`), true);
    await evaluate(`document.querySelector('#btn-clock').click()`);
    await waitFor(`document.querySelector('#clock-diagram .clock-node.primary')?.textContent.includes('400.00 MHz')`);
    assert.equal(await evaluate(`document.querySelector('.clock-pane').classList.contains('floating')`), true);
    assert.equal(await evaluate(`document.querySelector('#clock-diagram').textContent.includes('HCLK 200.00 MHz')`), true);
    assert.equal(await evaluate(`document.querySelector('#clock-diagram').textContent.includes('PCLK 100.00 MHz')`), true);
    await evaluate(`document.querySelector('#btn-clock').click()`);
    assert.equal(await evaluate(`document.querySelector('.clock-pane').hidden`), true);
    if (process.env.FORGE_TEST_WASM_BUILD === '1') {
      await evaluate(`document.querySelector('#btn-build').click()`);
      await waitFor(`document.querySelector('#term-build')?.textContent.includes('Build succeeded') || document.querySelector('#term-build')?.textContent.includes('Build failed')`, 180000);
      assert.equal(await evaluate(`document.querySelector('#term-build').textContent.includes('Build succeeded')`), true, await evaluate(`document.querySelector('#term-build').textContent`));
    }
    assert.deepEqual(errors, []);
  });
});
