#!/usr/bin/env python3
"""
Concatenates the IDE's ES modules into ide/forge.js, a classic script.
Browsers refuse to load module scripts from file://, so index.html uses the
bundle; the modules stay the source of truth (and are what the tests import).
"""
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
ORDER = [
    'ide/flash/an3155.js',
    'ide/flash/dfuse.js',
    'ide/flash/stlink.js',
    'ide/doom-sim.js',
    'ide/browser-build.js',
    'ide/c-sim.js',
    'ide/example-preview.js',
    'ide/source-search.js',
    'ide/clock-diagram.js',
    'ide/window-manager.js',
    'ide/app.js',
]


def main():
    parts = ['// Generated by tools/bundle_ide.py from ' + ', '.join(ORDER) + ' - do not edit.\n'
             '(() => {\n"use strict";\n']
    for rel in ORDER:
        with open(os.path.join(ROOT, rel)) as f:
            src = f.read()
        src = re.sub(r'^import [^;]+;\n', '', src, flags=re.M)
        src = re.sub(r'^export (?=(async )?(function|class|const|let)\b)', '', src, flags=re.M)
        parts.append('// ---- %s\n%s\n' % (rel, src))
    parts.append('})();\n')
    with open(os.path.join(ROOT, 'ide/forge.js'), 'w') as f:
        f.write(''.join(parts))
    print('wrote ide/forge.js')


if __name__ == '__main__':
    main()
